default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cobonline_development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: cobonline_test
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
